#!/usr/bin/env python3.11

from src.printer import printer
from src.analizer import analize
from src.flags import get_flags
import os


def main():
    directory_path = os.getcwd()
    flags = get_flags()
    analyze_result = analize(directory_path=directory_path, 
                             flags=flags)
    printer(analyze=analyze_result, 
            tree=flags.tree)
    
    
if __name__ == "__main__":
    main()